[build]
    functions = "functions"
    publish = "client/build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.production]
 publish = "client/build"
 command = "npm run build"