[build]
    functions = "functions"
    publish = "client/build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/"
    to = ".netlify/functions/index/:splat"
    status = 200